#/home/t1g3pf4c3/.config/nuga.yml

name: nuga
root: ~/projects/rocketsales


windows:
  - DO:
      layout: main-vertical
      panes:
      - db:
        - sshpass -p ${NUDODB} ssh -o stricthostkeychecking=no root@167.235.156.56 
      - service:
        - sshpass -p ${NUDOSERVICE} ssh -o stricthostkeychecking=no root@195.201.230.172 
  - source:
      layout: main-vertical
      panes:
      - db:
        - sshpass -p ${NUSDB} ssh -o stricthostkeychecking=no root@148.251.121.229
      - service:
        - sshpass -p ${NUSSERVICE} ssh -o stricthostkeychecking=no root@148.251.121.228
