set -g mouse on
set-option -g status-position top
set -g status-keys vi
set-window-option -g mode-keys vi
set-option -g history-limit 15000
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind s swap-window
bind j join-pane

bind -r | split-window -h -c "#{pane_current_path}"
bind -r - split-window -v -c "#{pane_current_path}"

bind < swap-pane -D
bind > swap-pane -U
# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

bind v copy-mode
bind V choose-buffer
bind S setw synchronize-panes
bind C-V pasteb
bind ";" next-layout
bind -r  r source-file ~/.tmux.conf
# mouse on

bind x kill-pane
bind & kill-window
bind T previous-window
bind  t next-window
bind C-c new-session

bind -T copy-mode-vi 'C-h' select-pane -L
bind -T copy-mode-vi 'C-j' select-pane -D
bind -T copy-mode-vi 'C-k' select-pane -U
bind -T copy-mode-vi 'C-l' select-pane -R
bind -T copy-mode-vi '^\' select-pane -l
bind -T copy-mode-vi 'C-Space' select-pane -t:.+
######

# SET STATUSBAR
bind-key b set status
# only show status bar if there is more then one window
set -g status off
set-hook -g after-new-window      'if "[ #{session_windows} -gt 1 ]" "set status on"'
set-hook -g after-kill-pane       'if "[ #{session_windows} -lt 2 ]" "set status off"'
set-hook -g pane-exited           'if "[ #{session_windows} -lt 2 ]" "set status off"'
set-hook -g window-layout-changed 'if "[ #{session_windows} -lt 2 ]" "set status off"'

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set-option -g automatic-rename-format "#{?#{==:#{b:pane_current_path},t1g3pf4c3},#{pane_current_command},#{b:pane_current_path}}"

# 
set -g status-fg "#928374"
set -g status-bg "#d5c4a1"
set-option -g status-left " #[fg=#7c6f64, bg=#d5c4a1, bold]#{session_name} "
set-option -g status-right "#[bold,fg=#ebdbb2, bg=#b16286 ] #{host} #{tmux_mode_indicator}" 
set-window-option -g window-status-current-format "#[bg=#fbf1c7, fg=#3c3836,bold,italics] #[noitalics]#[italics]#W#{?window_zoomed_flag,*Z,} "
set-window-option -g window-status-format "#[noitalics,bg=#bdae93,fg=#fbf1c7] #[noitalics]#W "
set-window-option -g window-status-separator ''
set-option -g window-style 'bg=#fbf1c7'
set-option -g pane-border-lines heavy
set-option -g pane-border-style 'fg=#ebdbb2, bg=#fbf1c7'
set-option -g pane-active-border-style 'fg=#b16286, bg=#fbf1c7'
set-option -g renumber-windows on




