# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "intel_pstate=passive"
    "i915.enable_fbc=1"
    "i915.enable_psr=2"
    "mem_sleep_default=deep"
    "pcie_aspm=force"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/12511272-604d-4a8e-a68e-fbec809988c9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D8DE-9967";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3ee11730-386f-4e31-8c86-4ee2932fdf46"; }];
  zramSwap.enable = true;

  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  networking.interfaces.wlan0.useDHCP = true;

  networking = {
    wireless.iwd.enable = true;
    networkmanager = {
      wifi.backend = "iwd";
      wifi.powersave = false;
    };
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware = {
    trackpoint = {
      enable = true;
      device = "Lenovo ThinkPad Compact USB Keyboard with TrackPoint";
      emulateWheel = false;
      sensitivity = 182;
      speed = 180;
    };
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl.extraPackages = with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau ];
    bluetooth.enable = true;
  };
}
